Repository Icinga/icingaweb2-module-reporting, pull requests merged in 2022-03, with the labels that each got.

#112 Adjust calls to CompatController::setTitle()
  application/controllers/ReportController.php
  application/controllers/ReportsController.php
  application/controllers/TemplatesController.php
  application/controllers/TestController.php
  application/controllers/TimeframeController.php
  application/controllers/TimeframesController.php
Labels: cla/signed

#114 Increase resources when producing reports
  application/controllers/ReportController.php
Labels: bug, cla/signed

#115 Enhance documentation
  application/forms/SelectBackendForm.php
  doc/02-Installation.md
  doc/03-Configuration.md
Labels: enhancement, area/documentation, cla/signed

#116 Support whitespace and comma separated e-mail recipients
  library/Reporting/Actions/SendMail.php
Labels: bug, cla/signed

#117 Only use `PDO::MYSQL_ATTR_INIT_COMMAND` for mysql connections
  library/Reporting/Database.php
Labels: bug, cla/signed

#64 Permissions
  application/controllers/ReportController.php
  application/controllers/ReportsController.php
  application/controllers/TemplateController.php
  application/controllers/TemplatesController.php
  application/controllers/TimeframeController.php
  application/controllers/TimeframesController.php
  configuration.php
  doc/03-Configuration.md
Labels: enhancement
