Repository Icinga/icingaweb2-module-reporting, pull requests merged in 2023-01, with the labels that each got.

#173 Update Checkout Action to v3
  .github/workflows/php.yml
Labels: cla/signed

#150 02-Installation.md: fix SQL GRANT example
  doc/02-Installation.md
Labels: bug, area/documentation, cla/signed

#162 ReportForm: Add description to the form elements
  library/Reporting/Web/Forms/ReportForm.php
Labels: enhancement, cla/signed

#176 PHP 8.2 Support
  .github/workflows/php.yml
Labels: cla/signed

#175 Add missing forms & controllers localization
  application/controllers/ReportController.php
  application/controllers/TemplatesController.php
  application/controllers/TestController.php
  library/Reporting/Web/Forms/ReportForm.php
  library/Reporting/Web/Forms/ScheduleForm.php
  library/Reporting/Web/Forms/SendForm.php
  library/Reporting/Web/Forms/TemplateForm.php
  library/Reporting/Web/Forms/TimeframeForm.php
Labels: bug, cla/signed
