Repository Icinga/icingaweb2-module-reporting, pull requests merged in 2023-10, with the labels that each got.

#204 Recommend package installs & enhance installation & configuration docs
  doc/01-About.md
  doc/02-Installation.md
  doc/02-Installation.md.d/From-Source.md
  doc/03-Configuration.md
Labels: enhancement, area/documentation, cla/signed

#209 Add base target `_main` to list controllers
  application/controllers/ReportsController.php
  application/controllers/TemplatesController.php
  library/Reporting/Model/Timeframe.php
  library/Reporting/Web/ReportsTimeframesAndTemplatesTabs.php
Labels: cla/signed

#211 Fix phpstan
  phpstan-baseline.neon
Labels: cla/signed

#212 Don't crash when failing to connect to the database
  application/clicommands/ScheduleCommand.php
Labels: bug, cla/signed

#213 doc: Fix postgres schema path
  doc/02-Installation.md
Labels: cla/signed

#214 doc: Drop package instructions
  doc/01-About.md
  doc/02-Installation.md
  doc/02-Installation.md.d/From-Source.md
  doc/03-Configuration.md
Labels: cla/signed

#215 Update references to the default branch
  .github/workflows/L10n-update.yml
  .github/workflows/php.yml
  README.md
Labels: cla/signed

#210 Release/1.0
  .gitignore
  .mailmap
  AUTHORS
  module.info
Labels: cla/signed
