Repository Icinga/icingaweb2-module-reporting, pull requests merged in 2023-03, with the labels that each got.

#181 CSS: Add css rule for `unknown` sla columns
  public/css/module.less
Labels: enhancement, cla/signed

#182 Use modals for `creating`, `editing` & `deleting` reports
  application/controllers/ReportController.php
  application/controllers/ReportsController.php
Labels: enhancement, cla/signed

#183 SendMail: Validate recipients mails
  library/Reporting/Actions/SendMail.php
Labels: enhancement, cla/signed

#137 ScheduleForm: Add `Send Report Now` button
  library/Reporting/Web/Forms/ScheduleForm.php
Labels: enhancement, cla/signed

#178 Drop usage of `flatpickr` in `TimeframeForm`
  application/controllers/TimeframeController.php
  application/controllers/TimeframesController.php
  library/Reporting/Web/Forms/TimeframeForm.php
Labels: bug, cla/signed

#139 Download command
  application/clicommands/DownloadCommand.php
  library/Reporting/Web/Forms/ReportForm.php
Labels: enhancement, cla/signed

#153 Use ipl orm
  application/clicommands/DownloadCommand.php
  application/controllers/ReportController.php
  application/controllers/ReportsController.php
  application/controllers/TemplateController.php
  application/controllers/TemplatesController.php
  application/controllers/TimeframeController.php
  application/controllers/TimeframesController.php
  library/Reporting/Model/Config.php
  library/Reporting/Model/Report.php
  library/Reporting/Model/Reportlet.php
  library/Reporting/Model/Schedule.php
  library/Reporting/Model/Template.php
  library/Reporting/Model/Timeframe.php
  library/Reporting/Report.php
  library/Reporting/Reportlet.php
  library/Reporting/Schedule.php
  library/Reporting/Scheduler.php
  library/Reporting/Timeframe.php
  library/Reporting/Web/Widget/Template.php
Labels: cla/signed

#143 Introduce cli list command
  application/clicommands/ListCommand.php
  doc/02-Installation.md
Labels: enhancement, cla/signed
