Repository Icinga/icingaweb2-module-reporting, pull requests merged in 2023-09, with the labels that each got.

#199 Use `style` element to create dynamic inline styles
  library/Reporting/Web/Widget/CoverPage.php
Labels: enhancement, cla/signed

#202 Don't populate `UploadedFile` on `text/select` elements & vice versa
  library/Reporting/Web/Forms/TemplateForm.php
Labels: bug, cla/signed

#187 Github Actions: Add Phpstan
  .github/workflows/php.yml
  application/clicommands/DownloadCommand.php
  application/clicommands/ListCommand.php
  application/controllers/ReportController.php
  application/controllers/ReportsController.php
  application/controllers/TemplateController.php
  application/controllers/TemplatesController.php
  application/controllers/TestController.php
  application/controllers/TimeframeController.php
  library/Reporting/Actions/SendMail.php
  library/Reporting/Database.php
  library/Reporting/Hook/ReportHook.php
  library/Reporting/Mail.php
  library/Reporting/Reportlet.php
  library/Reporting/Schedule.php
  library/Reporting/Web/Forms/ReportForm.php
  library/Reporting/Web/Forms/ScheduleForm.php
  library/Reporting/Web/Forms/TemplateForm.php
  library/Reporting/Web/Forms/TimeframeForm.php
  library/Reporting/Web/Widget/HeaderOrFooter.php
  phpstan-baseline.neon
  phpstan.neon
Labels: enhancement, cla/signed

#203 Use `StyleWithNonce` element
  library/Reporting/Web/Widget/CoverPage.php
Labels: cla/signed

#194 Enhance modal form redirects
  application/controllers/ReportController.php
  application/controllers/ReportsController.php
  application/controllers/TemplateController.php
  application/controllers/TemplatesController.php
  application/controllers/TimeframeController.php
  application/controllers/TimeframesController.php
  library/Reporting/Model/Report.php
  library/Reporting/Web/Forms/ReportForm.php
  library/Reporting/Web/Forms/TemplateForm.php
  phpstan-baseline.neon
  phpstan.neon
  public/css/module.less
Labels: enhancement, cla/signed

#206 Drop ignore error pattern matching `Model::{getKeyName(), getColumns()}`
  phpstan-baseline.neon
Labels: cla/signed

#208 Don't render report `mtime` multiple times
  application/controllers/ReportsController.php
Labels: bug, cla/signed

#188 Provide migration hook
  doc/80-Upgrading.md
  library/Reporting/Database.php
  library/Reporting/Model/Schedule.php
  library/Reporting/Model/Schema.php
  library/Reporting/ProvidedHook/DbMigration.php
  phpstan-baseline.neon
  run.php
  schema/mysql-upgrades/1.0.0.sql
  schema/mysql.schema.sql
  schema/pgsql-upgrades/1.0.0.sql
  schema/pgsql.schema.sql
Labels: enhancement, cla/signed
