Repository Icinga/icingaweb2-module-reporting, pull requests merged in 2024-05, with the labels that each got.

#232 Phpstan: Separate workflow
  .github/workflows/php.yml
  .github/workflows/phpstan.yml
Labels: enhancement, cla/signed

#231 SendMail: Send PDFs asynchronously
  library/Reporting/Actions/SendMail.php
Labels: bug, cla/signed

#235 DbMigration: Break once a correct schema version is found
  library/Reporting/ProvidedHook/DbMigration.php
Labels: bug, cla/signed

#237 Cleanup code
  application/controllers/ConfigController.php
  application/controllers/PlugController.php.disabled
  application/controllers/ReportController.php
  application/controllers/ReportController.php.modal
  application/controllers/ReportsController.php
  application/controllers/TemplateController.php
  application/controllers/TemplatesController.php
  application/controllers/TimeframeController.php
  application/controllers/TimeframesController.php
  library/Reporting/Web/Forms/ReportForm.php
  library/Reporting/Web/Forms/ScheduleForm.php
  library/Reporting/Web/Forms/TemplateForm.php
  library/Reporting/Web/Forms/TimeframeForm.php
  phpstan-baseline.neon
Labels: cla/signed

#236 Release v1.0.2
  module.info
Labels: cla/signed
